[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license-file.workspace = true
name = "ach-ring"
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
util = {package = "ach-util", version = "0.2", path = "../ach-util"}

[target.'cfg(target_os = "none")'.dependencies]
interrupt = "0.1"

[dev-dependencies]
criterion = "0.8"
crossbeam-queue = "0.3.4"
crossbeam-utils = "0.8.7"
flume = "0.12"
on_drop = "0.1"

[[bench]]
harness = false
name = "basic"
