[package]
authors = ["rise0chen <rise0chen@163.com>"]
categories = ["concurrency"]
description = "spin_loop"
edition = "2018"
keywords = ["spin"]
license-file = "LICENSE"
name = "spin_loop"
readme = "./README.md"
repository = "https://github.com/rise0chen/ach.git"
version = "0.1.1"
