[package]
authors.workspace = true
categories = ["embedded", "concurrency"]
description = "interrupt"
edition.workspace = true
keywords = ["interrupt"]
license-file.workspace = true
name = "interrupt"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
custom = []
default = []

[dependencies]
bare-metal = "0.2"
cfg-if = "1.0.0"

[target.'cfg(all(target_arch = "arm", target_os = "none"))'.dependencies]
cortex-m = {version = "0"}
[target.'cfg(all(any(target_arch = "riscv32", target_arch = "riscv64"), target_os = "none"))'.dependencies]
riscv = {version = "0"}
[target.'cfg(all(target_arch = "msp430", target_os = "none"))'.dependencies]
msp430 = {version = "0"}
[target.'cfg(all(target_arch = "xtensa", target_os = "none"))'.dependencies]
xtensa-lx = {version = "0"}

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
